### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '**.png'

### ISSUE THREAD

**Issue by guangxuwang** [lkeab/BCNet#104]
When i trained in mydataset or COCO dataset，FileNotFoundError: [Errno 2] No such file or directory: '**.png'

[05/01 19:51:46 d2.engine.train_loop]: Starting training from iteration 0
<generator object AspectRatioGroupedDataset.__iter__ at 0x7fd48c136150>
[05/01 19:52:09 d2.engine.hooks]: Total training time: 0:00:22 (0:00:00 on hooks)
[05/01 19:52:09 d2.data.datasets.coco]: Loaded 20 images in COCO format from datasets/cocococo/annotations/instances_val2017.json
[05/01 19:52:09 d2.data.build]: Distribution of instances among all 1 categories:
|  category  | #instances   |
|:----------:|:-------------|
|    fish    | 896          |
|            |              |
[05/01 19:52:09 d2.data.common]: Serializing 20 elements to byte tensors and concatenating them all ...
[05/01 19:52:09 d2.data.common]: Serialized dataset takes 0.33 MiB
[05/01 19:52:09 d2.evaluation.evaluator]: Start inference on 10 images
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/engine/launch.py", line 48, in launch
    daemon=False,
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/engine/train_loop.py", line 206, in run_step
    data = next(self._data_loader_iter)
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/data/common.py", line 139, in __iter__
    for d in self.dataset:
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/data/common.py", line 40, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/data/dataset_mapper.py", line 76, in __call__
    image = utils.read_image(dataset_dict["file_name"], format=self.img_format)
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/data/detection_utils.py", line 53, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/iopath-0.1.9-py3.7.egg/iopath/common/file_io.py", line 1012, in      open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/iopath-0.1.9-py3.7.egg/iopath/common/file_io.py", line 612, in _     open
    opener=opener,
FileNotFoundError: [Errno 2] No such file or directory: '46.png'

**Comment by lkeab** [comment]
can you print the "file_name" at "/wwwroot/wangguangxu/BCNet-main/detectron2/data/detection_utils.py", line53, to debug?

**Comment by guangxuwang** [comment]
> can you print the "file_name" at "/wwwroot/wangguangxu/BCNet-main/detectron2/data/detection_utils.py", line53, to debug?

i rewrite the code of reading image，but RuntimeError: CUDA error: invalid device function (ROIAlign_forward_cuda at /wwwroot/wangguangxu/BCNet-main/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:361)




[05/02 22:30:30 d2.engine.train_loop]: Starting training from iteration 0
<generator object AspectRatioGroupedDataset.__iter__ at 0x7f999c1361d0>
<generator object AspectRatioGroupedDataset.__iter__ at 0x7f761ab97c50>
[05/02 22:31:04 d2.engine.hooks]: Total training time: 0:00:33 (0:00:00 on hooks)
[05/02 22:31:04 d2.data.datasets.coco]: Loaded 20 images in COCO format from datasets/cocococo/annotations/instances_val                 2017.json
[05/02 22:31:04 d2.data.build]: Distribution of instances among all 1 categories:
|  category  | #instances   |
|:----------:|:-------------|
|    fish    | 896          |
|            |              |
[05/02 22:31:04 d2.data.common]: Serializing 20 elements to byte tensors and concatenating them all ...
[05/02 22:31:04 d2.data.common]: Serialized dataset takes 0.33 MiB
[05/02 22:31:04 d2.evaluation.evaluator]: Start inference on 10 images
/wwwroot/wangguangxu/BCNet-main/datasets/cocococo/val2017/51.png
/wwwroot/wangguangxu/BCNet-main/datasets/cocococo/val2017/71.png
/wwwroot/wangguangxu/BCNet-main/datasets/cocococo/val2017/72.png
/wwwroot/wangguangxu/BCNet-main/datasets/cocococo/val2017/85.png
/wwwroot/wangguangxu/BCNet-main/datasets/cocococo/val2017/84.png
/wwwroot/wangguangxu/BCNet-main/datasets/cocococo/val2017/68.png
/wwwroot/wangguangxu/BCNet-main/datasets/cocococo/val2017/49.png
/wwwroot/wangguangxu/BCNet-main/datasets/cocococo/val2017/94.png
/wwwroot/wangguangxu/BCNet-main/datasets/cocococo/val2017/48.png
/wwwroot/wangguangxu/BCNet-main/datasets/cocococo/val2017/89.png
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/engine/launch.py", line 48, in launch
    daemon=False,
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in                  spawn
    while not spawn_context.join():
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in                  join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/engine/train_loop.py", line 212, in run_step
    loss_dict = self.model(data, self.iter, self.max_iter)
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __c                 all__
    result = self.forward(*input, **kwargs)
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447,                  in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __c                 all__
    result = self.forward(*input, **kwargs)
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/modeling/meta_arch/fcos.py", line 176, in forward
    centerness, gt_instances, batched_inputs, images, c_iter, max_iter
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/modeling/meta_arch/fcos.py", line 199, in _forward_train
    loss_mask, loss_mask_bo, loss_boundary, loss_boundary_bo = self._forward_mask(features_list, proposals)
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/modeling/meta_arch/fcos.py", line 245, in _forward_mask
    mask_features = self.mask_pooler(features, proposal_boxes)
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __c                 all__
    result = self.forward(*input, **kwargs)
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/modeling/poolers.py", line 232, in forward
    output[inds] = pooler(x_level, pooler_fmt_boxes_level)
  File "/home/wangguangxu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __c                 all__
    result = self.forward(*input, **kwargs)
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/layers/roi_align.py", line 94, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio, self.aligned
  File "/wwwroot/wangguangxu/BCNet-main/detectron2/layers/roi_align.py", line 19, in forward
    input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio, aligned
RuntimeError: CUDA error: invalid device function (ROIAlign_forward_cuda at /wwwroot/wangguangxu/BCNet-main/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:361)

**Comment by guangxuwang** [comment]
> can you print the "file_name" at "/wwwroot/wangguangxu/BCNet-main/detectron2/data/detection_utils.py", line53, to debug?
![image](https://user-images.githubusercontent.com/104683713/166253824-9af9912a-8a2d-45ba-9f0e-79c6e976b5ae.png)

**Comment by lkeab** [comment]
this is becuase of the wrong cuda version. Please make sure your environment matches "conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch".  You can also refer to the discussion [here](https://github.com/facebookresearch/detectron2/issues/62).
