### ISSUE TITLE
Checkpoint not found issue

### ISSUE THREAD

**Issue by suresh-s** [lkeab/BCNet#12]
I appreciate the good work!. 

I try to explore the code and try to train. I am getting the following error message.  what should i do to fix the issue

**AssertionError: Checkpoint "detectron2://ImageNetPretrained/MSRA/R-101.pkl" not found!**

**Comment by lkeab** [comment]
Thanks for watching our work. This pkl file will be automatically downloaded running detectron2. Does your server have network connection? The issue could be related to your installation or environment setup. You could also manually download it at https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MSRA/R-101.pkl.

**Comment by suresh-s** [comment]
Thank your for your quick response!

The server has internet connection.  below is the error trace

```
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/D/source/BCNet/detectron2/engine/launch.py", line 48, in launch
    daemon=False,
  File "/home/administrator/.virtualenvs/bcnet_env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/administrator/.virtualenvs/bcnet_env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/administrator/.virtualenvs/bcnet_env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/D/source/BCNet/detectron2/engine/launch.py", line 83, in _distributed_worker
    main_func(*args)
  File "/D/source/BCNet/tools/train_net.py", line 144, in main
    trainer.resume_or_load(resume=args.resume)
  File "/D/source/BCNet/detectron2/engine/defaults.py", line 283, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume).get(
  File "/home/administrator/.virtualenvs/bcnet_env/lib/python3.6/site-packages/fvcore-0.1.5.post20210515-py3.6.egg/fvcore/common/checkpoint.py", line 215, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/administrator/.virtualenvs/bcnet_env/lib/python3.6/site-packages/fvcore-0.1.5.post20210515-py3.6.egg/fvcore/common/checkpoint.py", line 141, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint detectron2://ImageNetPretrained/MSRA/R-101.pkl not found!
```

I am new to this environment.  I am having CUDA 10.0, torch 1.4.0 and torchvision 0.5.0 and followed mentioned installation procedure.

Could you help me to debug this environment issue?

**Comment by lkeab** [comment]
You could replace the "detectron2:// path" with your defined local path in the code by modifing the checkpoint.py, such as /path/to/ImageNetPretrained/MSRA/R-101.pkl.

Also, you could refer to the solution [here](https://github.com/Majiker/BalancedMetaSoftmax-InstanceSeg/issues/3)

**Comment by leedoge** [comment]
> Thanks for watching our work. This pkl file will be automatically downloaded running detectron2. Does your server have network connection? The issue could be related to your installation or environment setup. You could also manually download it at https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MSRA/R-101.pkl.

hello!Could you please provide the download address of Checkpoint detectron2://ImageNetPretrained/MSRA/R-50.pkl ?
I have the same problem.Thank you very much

**Comment by hayatkhan8660-maker** [comment]
I solved it :)
