### ISSUE TITLE
training

### ISSUE THREAD

**Issue by liujie1202** [lkeab/BCNet#19]
你好，整个训练的顺序是按照您发的readme文件吗？我按照上面的这个步骤进行了安装环境，接着安装了CoCo数据集，我在执行bash all.sh时出现了下面的错误。这是什么地方的问题呀
Using /home/lab409/anaconda3/envs/bcnet/lib/python3.7/site-packages/oauthlib-3.1.0-py3.7.egg
Finished processing dependencies for detectron2==0.1
tee: log/train_log_159.txt: 没有那个文件或目录
Command Line Args: Namespace(config_file='configs/fcos/fcos_imprv_R_50_FPN_1x.yaml', dist_url='tcp://127.0.0.1:50152', eval_only=False, machine_rank=0, num_gpus=2, num_machines=1, opts=[], resume=False)
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/home/lab409/BCNet-main /BCNet-main/detectron2/engine/launch.py", line 48, in launch
    daemon=False,
  File "/home/lab409/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/lab409/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/lab409/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/lab409/BCNet-main /BCNet-main/detectron2/engine/launch.py", line 71, in _distributed_worker
    assert num_gpus_per_machine <= torch.cuda.device_count()
AssertionError

**Comment by lkeab** [comment]
the number of required gpus is larger than the actual gpu number.
