### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

### ISSUE THREAD

**Issue by lqzhao** [lkeab/BCNet#25]
I run the command like:  `CUDA_VISIBLE_DEVICES=2,3 python tools/train_net.py --num-gpus 2 --config-file configs/fcos/fcos_imprv_R_50_FPN.yaml 2>&1 | tee log/train_log.tx`
After the Evaluation, we got a problem about cuDNN.

**[05/31 13:10:41 d2.evaluation.coco_evaluation]: Evaluation results for segm: 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
|:-----:|:------:|:------:|:-----:|:-----:|:-----:|
| 0.000 | 0.000  | 0.000  | 0.000 | 0.000 | 0.000 |
[05/31 13:10:41 d2.evaluation.coco_evaluation]: Per-category segm AP: 
| category      | AP    | category     | AP    | category       | AP    |
|:--------------|:------|:-------------|:------|:---------------|:------|
| person        | 0.000 | bicycle      | 0.000 | car            | 0.000 |
| motorcycle    | 0.000 | airplane     | 0.000 | bus            | 0.000 |
| train         | 0.000 | truck        | 0.000 | boat           | 0.000 |
| traffic light | 0.000 | fire hydrant | 0.000 | stop sign      | 0.000 |
| parking meter | 0.000 | bench        | 0.000 | bird           | 0.000 |
| cat           | 0.000 | dog          | 0.000 | horse          | 0.000 |
| sheep         | 0.000 | cow          | 0.000 | elephant       | 0.000 |
| bear          | 0.000 | zebra        | 0.000 | giraffe        | 0.000 |
| backpack      | 0.000 | umbrella     | 0.000 | handbag        | 0.000 |
| tie           | 0.000 | suitcase     | 0.000 | frisbee        | 0.000 |
| skis          | 0.000 | snowboard    | 0.000 | sports ball    | 0.000 |
| kite          | 0.000 | baseball bat | 0.000 | baseball glove | 0.000 |
| skateboard    | 0.000 | surfboard    | 0.000 | tennis racket  | 0.000 |
| bottle        | 0.000 | wine glass   | 0.000 | cup            | 0.000 |
| fork          | 0.000 | knife        | 0.000 | spoon          | 0.000 |
| bowl          | 0.000 | banana       | 0.000 | apple          | 0.000 |
| sandwich      | 0.000 | orange       | 0.000 | broccoli       | 0.000 |
| carrot        | 0.000 | hot dog      | 0.000 | pizza          | 0.000 |
| donut         | 0.000 | cake         | 0.000 | chair          | 0.000 |
| couch         | 0.000 | potted plant | 0.000 | bed            | 0.000 |
| dining table  | 0.000 | toilet       | 0.000 | tv             | 0.000 |
| laptop        | 0.000 | mouse        | 0.000 | remote         | 0.000 |
| keyboard      | 0.000 | cell phone   | 0.000 | microwave      | 0.000 |
| oven          | 0.000 | toaster      | 0.000 | sink           | 0.000 |
| refrigerator  | 0.000 | book         | 0.000 | clock          | 0.000 |
| vase          | 0.000 | scissors     | 0.000 | teddy bear     | 0.000 |
| hair drier    | 0.000 | toothbrush   | 0.000 |                |       |
[05/31 13:10:42 d2.engine.defaults]: Evaluation results for coco_2017_val in csv format:
[05/31 13:10:42 d2.evaluation.testing]: copypaste: Task: bbox
[05/31 13:10:42 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[05/31 13:10:42 d2.evaluation.testing]: copypaste: 0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
[05/31 13:10:42 d2.evaluation.testing]: copypaste: Task: segm
[05/31 13:10:42 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[05/31 13:10:42 d2.evaluation.testing]: copypaste: 0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/data/zlq/code/BCNet-main/detectron2/engine/launch.py", line 48, in launch
    daemon=False,
  File "/home/zlq/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/zlq/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/zlq/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/zlq/code/BCNet-main/detectron2/engine/launch.py", line 83, in _distributed_worker
    main_func(*args)
  File "/data/zlq/code/BCNet-main/tools/train_net.py", line 149, in main
    return trainer.train()
  File "/data/zlq/code/BCNet-main/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/data/zlq/code/BCNet-main/detectron2/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/data/zlq/code/BCNet-main/detectron2/engine/train_loop.py", line 224, in run_step
    losses.backward()
  File "/home/zlq/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zlq/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.**

I followed the Step-by-step Installation. 
Pytorch 1.4 .0
torchvision 0.5.0
cudatoolkit 10.1

Did anyone meet this problem before?
Is this a version problem? [https://github.com/pytorch/pytorch/issues/32395](url)

**Comment by lkeab** [comment]
Maybe the answer under this (issue)[https://github.com/pytorch/pytorch/issues/32564#issuecomment-635062872] will help

**Comment by heizie** [comment]
> Maybe the answer under this [issue](https://github.com/pytorch/pytorch/issues/32564#issuecomment-635062872) will help

Nope. i've tried reduced the batch size to 1. using Quadro RTX 5000 (16GB) still get to same error.
I've upgraded the pytorch to 1.7. But you're using a acient Version of detectron 2. it didn't support that.

I don't know why someone else can train with their own dataset....

**Comment by qgq99** [comment]
Have you finally solved this problem? I am suffering it and reducing batch-size does not work.
