### ISSUE TITLE
KeyError:'bg_object_segmentation'. 

### ISSUE THREAD

**Issue by tangmao2019** [lkeab/BCNet#37]
Thank you for the open source code.
I use the coco dataset for training, and the annotation file is instances_train_2017_transform_slight_correct.json. 
There was an KeyError:'bg_object_segmentation'. 
I checked ‘dataset_dict’ and found that the annotation in ‘dataset_dict’ does not contain bg_object_segmentation，but when I  open instances_train_2017_transform_slight_correct.json, there is bg_object_segmentation in 'instances_train_2017_transform_slight_correct.json'.

The error message is below：

[07/09 16:47:33 d2.engine.train_loop]: Starting training from iteration 0
<generator object AspectRatioGroupedDataset.__iter__ at 0x7f1f3e3c4c50>
[07/09 16:47:34 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
Traceback (most recent call last):
  File "/media/lc/files/YLQ/BCNet-main/detectron2/engine/train_loop.py", line 133, in train
    self.run_step()
  File "/media/lc/files/YLQ/BCNet-main/detectron2/engine/train_loop.py", line 212, in run_step
    data = next(self._data_loader_iter)
  File "/media/lc/files/YLQ/BCNet-main/detectron2/data/common.py", line 139, in __iter__
    for d in self.dataset:
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/lc/files/YLQ/BCNet-main/detectron2/data/common.py", line 40, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/media/lc/files/YLQ/BCNet-main/detectron2/utils/serialize.py", line 22, in __call__
    return self._obj(*args, **kwargs)
  File "/media/lc/files/YLQ/BCNet-main/detectron2/data/dataset_mapper.py", line 134, in __call__
    annos, image_shape, mask_format=self.mask_format
  File "/media/lc/files/YLQ/BCNet-main/detectron2/data/detection_utils.py", line 278, in annotations_to_instances
    bo_segms = [obj["bg_object_segmentation"] for obj in annos]
  File "/media/lc/files/YLQ/BCNet-main/detectron2/data/detection_utils.py", line 278, in <listcomp>
    bo_segms = [obj["bg_object_segmentation"] for obj in annos]
KeyError: 'bg_object_segmentation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/lc/files/YLQ/BCNet-main/tools/train_net.py", line 164, in <module>
    args=(args,),
  File "/media/lc/files/YLQ/BCNet-main/detectron2/engine/launch.py", line 51, in launch
    main_func(*args)
  File "/media/lc/files/YLQ/BCNet-main/tools/train_net.py", line 151, in main
    return trainer.train()
  File "/media/lc/files/YLQ/BCNet-main/detectron2/engine/defaults.py", line 384, in train
    super().train(self.start_iter, self.max_iter)
  File "/media/lc/files/YLQ/BCNet-main/detectron2/engine/train_loop.py", line 136, in train
    self.after_train()
  File "/media/lc/files/YLQ/BCNet-main/detectron2/engine/train_loop.py", line 144, in after_train
    h.after_train()
  File "/media/lc/files/YLQ/BCNet-main/detectron2/engine/hooks.py", line 353, in after_train
    self._do_eval()
  File "/media/lc/files/YLQ/BCNet-main/detectron2/engine/hooks.py", line 321, in _do_eval
    results = self._func()
  File "/media/lc/files/YLQ/BCNet-main/detectron2/engine/defaults.py", line 335, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/media/lc/files/YLQ/BCNet-main/detectron2/engine/defaults.py", line 480, in test
    data_loader = cls.build_test_loader(cfg, dataset_name)
  File "/media/lc/files/YLQ/BCNet-main/detectron2/engine/defaults.py", line 442, in build_test_loader
    return build_detection_test_loader(cfg, dataset_name)
  File "/media/lc/files/YLQ/BCNet-main/detectron2/data/build.py", line 386, in build_detection_test_loader
    else None,
  File "/media/lc/files/YLQ/BCNet-main/detectron2/data/build.py", line 230, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/media/lc/files/YLQ/BCNet-main/detectron2/data/build.py", line 230, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/media/lc/files/YLQ/BCNet-main/detectron2/data/catalog.py", line 65, in get
    return f()
  File "/media/lc/files/YLQ/BCNet-main/detectron2/data/datasets/register_coco.py", line 35, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json_eval(json_file, image_root, name))
  File "/media/lc/files/YLQ/BCNet-main/detectron2/data/datasets/coco.py", line 57, in load_coco_json_eval
    coco_api = COCO(json_file)
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/site-packages/pycocotools/coco.py", line 85, in __init__
    dataset = json.load(f)
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/lc/anaconda3/envs/bcnet/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 205 (char 204)

Process finished with exit code 1

**Comment by lkeab** [comment]
That's strange. Could you make sure this [line](https://github.com/lkeab/BCNet/blob/main/detectron2/data/datasets/builtin.py#L42) is executed and you read the correct (our provided) json file?
