### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 188829059 (char 188829058)

### ISSUE THREAD

**Issue by DonaldKam** [lkeab/BCNet#44]
Really hope that you (@lkeab ) can spend some time in checking my problem as follows:
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/gpfs1/home/BCNet/detectron2/engine/launch.py", line 48, in launch
    daemon=False,
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/gpfs1/home/BCNet/detectron2/engine/launch.py", line 83, in _distributed_worker
    main_func(*args)
  File "/gpfs1/home//BCNet/tools/train_net.py", line 143, in main
    trainer = Trainer(cfg)
  File "/gpfs1/home/BCNet/detectron2/engine/defaults.py", line 246, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/gpfs1/home/BCNet/detectron2/engine/defaults.py", line 420, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/gpfs1/home/BCNet/detectron2/data/build.py", line 306, in build_detection_train_loader
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/gpfs1/home/BCNet/detectron2/data/build.py", line 226, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/gpfs1/home/BCNet/detectron2/data/build.py", line 226, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/gpfs1/home/BCNet/detectron2/data/catalog.py", line 61, in get
    return f()
  File "/gpfs1/home/BCNet/detectron2/data/datasets/register_coco.py", line 33, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/gpfs1/home/BCNet/detectron2/data/datasets/coco.py", line 226, in load_coco_json
    coco_api = COCO(json_file)
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
  File "/home/anaconda3/envs/bcnet/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/anaconda3/envs/bcnet/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/homeanaconda3/envs/bcnet/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/anaconda3/envs/bcnet/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 188829059 (char 188829058)

**Comment by lkeab** [comment]
which json did you use? any json related modifications?

**Comment by DonaldKam** [comment]
![image](https://user-images.githubusercontent.com/44252954/127863147-883bab84-e984-479d-a0da-6de8ac214dbb.png)
![image](https://user-images.githubusercontent.com/44252954/127863321-949d38b3-d499-4948-8f08-72cf51618047.png)
I used the downloaded converted coco annotation without modification.

**Comment by lkeab** [comment]
"json.decoder.JSONDecodeError: Expecting value: line 1 column 188829059 (char 188829058)". It seems the downloaded json is broken with one char difference?

**Comment by lkeab** [comment]
Also make sure the encoding is "UTF-8". such as: with open("xxx.json", encoding='utf-8') as json_data:

**Comment by DonaldKam** [comment]
Thanks for prompt reply. I am concerned about how you deal with a object **A** that is occluded by a non-object **B** ? And the object **A** is segmented into multiple parts by **B**. P.S: B is foreground object is not annotated in the image.

**Comment by lkeab** [comment]
In this case, A will be in the second gcn layer and the object B (not in the annotation and not be detected) will be in the first GCN and assigned empty masks, where the bilayer decoupling segmentation will degrade to the normal maskrcnn segmentation style.
 
For more discussions, you could also refer to the issue [here](https://github.com/lkeab/BCNet/issues/11).
