### ISSUE TITLE
I meet RuntimeError:RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

### ISSUE THREAD

**Issue by ZeyuMa-Uestc** [lkeab/BCNet#51]
This is config:
Traceback (most recent call last):
  File "tools/train_net.py", line 162, in <module>
    args=(args,),
  File "/data1/mazeyu/BCNet-main/detectron2/engine/launch.py", line 48, in launch
    daemon=False,
  File "/home/mazeyu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/mazeyu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/mazeyu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data1/mazeyu/BCNet-main/detectron2/engine/launch.py", line 83, in _distributed_worker
    main_func(*args)
  File "/data1/mazeyu/BCNet-main/tools/train_net.py", line 150, in main
    return trainer.train()
  File "/data1/mazeyu/BCNet-main/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/data1/mazeyu/BCNet-main/detectron2/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/data1/mazeyu/BCNet-main/detectron2/engine/train_loop.py", line 224, in run_step
    losses.backward()
  File "/home/mazeyu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/mazeyu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

I change batch_size , but not work, please help me.

**Comment by lkeab** [comment]
Hi, thanks for watching our work. Please refer to the issue discussion [here](https://github.com/lkeab/BCNet/issues/39).

**Comment by ZeyuMa-Uestc** [comment]
thank you!
