### ISSUE TITLE
Timed out waiting 1800000ms for send operation to complete

### ISSUE THREAD

**Issue by ZeyuMa-Uestc** [lkeab/BCNet#53]
Hi I meet a bug：RuntimeError: Application timeout caused pair closure。
This is config：
Traceback (most recent call last):
  File "tools/train_net.py", line 162, in <module>
    args=(args,),
  File "/data1/mazeyu/BCNet-main/detectron2/engine/launch.py", line 48, in launch
    daemon=False,
  File "/home/mazeyu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/mazeyu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/data1/mazeyu/BCNet-main/detectron2/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/data1/mazeyu/BCNet-main/detectron2/engine/train_loop.py", line 218, in run_step
    self._write_metrics(metrics_dict)
  File "/data1/mazeyu/BCNet-main/detectron2/engine/train_loop.py", line 253, in _write_metrics
    all_metrics_dict = comm.gather(metrics_dict)
  File "/data1/mazeyu/BCNet-main/detectron2/utils/comm.py", line 199, in gather
    size_list, tensor = _pad_to_largest_tensor(tensor, group)
  File "/data1/mazeyu/BCNet-main/detectron2/utils/comm.py", line 125, in _pad_to_largest_tensor
    dist.all_gather(size_list, local_size, group=group)
  File "/home/mazeyu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1158, in all_gather
    work.wait()
RuntimeError: [/opt/conda/conda-bld/pytorch_1579022060824/work/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:136] Timed out waiting 1800000ms for send operation to complete

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mazeyu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data1/mazeyu/BCNet-main/detectron2/engine/launch.py", line 83, in _distributed_worker
    main_func(*args)
  File "/data1/mazeyu/BCNet-main/tools/train_net.py", line 150, in main
    return trainer.train()
  File "/data1/mazeyu/BCNet-main/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/data1/mazeyu/BCNet-main/detectron2/engine/train_loop.py", line 134, in train
    self.after_train()
  File "/data1/mazeyu/BCNet-main/detectron2/engine/train_loop.py", line 142, in after_train
    h.after_train()
  File "/data1/mazeyu/BCNet-main/detectron2/engine/hooks.py", line 353, in after_train
    self._do_eval()
  File "/data1/mazeyu/BCNet-main/detectron2/engine/hooks.py", line 321, in _do_eval
    results = self._func()
  File "/data1/mazeyu/BCNet-main/detectron2/engine/defaults.py", line 324, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/data1/mazeyu/BCNet-main/detectron2/engine/defaults.py", line 484, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/data1/mazeyu/BCNet-main/detectron2/evaluation/evaluator.py", line 157, in inference_on_dataset
    results = evaluator.evaluate()
  File "/data1/mazeyu/BCNet-main/detectron2/evaluation/coco_evaluation.py", line 120, in evaluate
    predictions = comm.gather(self._predictions, dst=0)
  File "/data1/mazeyu/BCNet-main/detectron2/utils/comm.py", line 199, in gather
    size_list, tensor = _pad_to_largest_tensor(tensor, group)
  File "/data1/mazeyu/BCNet-main/detectron2/utils/comm.py", line 125, in _pad_to_largest_tensor
    dist.all_gather(size_list, local_size, group=group)
  File "/home/mazeyu/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1158, in all_gather
    work.wait()
RuntimeError: Application timeout caused pair closure

Please help me，thanks！

**Comment by lkeab** [comment]
It seems the problem of 'communications between different processes'. How many GPUs are you using? Do you meet out of memory problem?

**Comment by ZeyuMa-Uestc** [comment]
I use 4 2080ti, I don't meet out of memory problem. When batch size is 4, I can start training from iteration 0. But I  met this problem when iteration 1 began. I had set batch size to 8 ,I don't meet this problem for the time being.

**Comment by ZeyuMa-Uestc** [comment]
When batch size is 4, there is a bug.

**Comment by Auroralyxa** [comment]
Hi,
I get the error as below
`RuntimeError: [..\third_party\gloo\gloo\transport\uv\unbound_buffer.cc:67] Timed out waiting 1800000ms for recv operation to complete`
May I ask how did you solve the error?

**Comment by ywwwei** [comment]
I got the same error. How did you solve it? Thanks! @Martin0401

**Comment by rentainhe** [comment]
I got the same error. How did you solve it? @Martin0401

**Comment by Auroralyxa** [comment]
sorry,i didn't solve it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ren ***@***.***&gt;; 
发送时间: 2022年9月6日(星期二) 下午3:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lkeab/BCNet] Timed out waiting 1800000ms for send operation to complete (#53)





 
I got the same error. How did you solve it? @Martin0401

**Comment by rentainhe** [comment]
> 

Thanks a lot ~, I've no idea how to solve this too~ : (
if you find any solutions, please contact me, thank you~

**Comment by jeya-maria-jose** [comment]
Changing the default timeout state in your distributed initialization solved this issue for me. The default is timeout is 1800 seconds, just set it to a higher value according to your need. For example, `dist.init_process_group(backend=backend, timeout=datetime.timedelta(seconds=100000) **kwargs)`

**Comment by zwxandy** [comment]
> Changing the default timeout state in your distributed initialization solved this issue for me. The default is timeout is 1800 seconds, just set it to a higher value according to your need. For example, `dist.init_process_group(backend=backend, timeout=datetime.timedelta(seconds=100000) **kwargs)`

This also works for me. At least, my program is running now. But maybe there are some hidden bugs in the framework or code.
