### ISSUE TITLE
Detector：retinanet

### ISSUE THREAD

**Issue by cp1108** [lkeab/BCNet#73]
BCNet-main/configs/Base-FCOS.yaml  作者您好，在该文件中第5行，NAME: "build_retinanet_resnet_fpn_backbone"，如果我想将Detector改成faster-rcnn，请问需要修改哪些内容呢

**Comment by cp1108** [comment]
想麻烦您能否提供一份faster-rcnn的config

**Comment by lkeab** [comment]
hi, you could find the config for faster rcnn at detectron2 repo. My suggestion is that, you replace the maskhead of detectron2 implementation with ours. Faster-rcnn is their default detector usage.

**Comment by cp1108** [comment]
thanks

**Comment by cp1108** [comment]
#43 “It is contained in the code here. You just need to modify the config to use faster rcnn instead of fcos as object dectecter.” 您好，在这个Issues的最后您回复说只需要modify the config即可，我使用了detectron2的官方faster-rcnn config，但运行时出现了error。config设置如下：
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2



# FCOS with improvements
_BASE_: "/home/prj/BCNet-main/configs/base.yaml"
MODEL:
  WEIGHTS: "/home/github/R-101.pkl"
  RESNETS:
    DEPTH: 101
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 21
DATASETS:
  TRAIN: ('bop_train',)
  TEST: ('bop_val',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (1300,1500)
  MAX_ITER: 2000  # 17.4 epochs
  WARMUP_ITERS: 100

error：
Traceback (most recent call last):
  File "/home/prj/BCNet-main/detectron2/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/home/prj/BCNet-main/detectron2/engine/train_loop.py", line 213, in run_step
    loss_dict = self.model(data, self.iter, self.max_iter)
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/prj/BCNet-main/detectron2/engine/launch.py", line 83, in _distributed_worker
    main_func(*args)
  File "/home/prj/BCNet-main/train.py", line 470, in main
    return trainer.train()
  File "/home/prj/BCNet-main/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/prj/BCNet-main/detectron2/engine/train_loop.py", line 134, in train
    self.after_train()
  File "/home/prj/BCNet-main/detectron2/engine/train_loop.py", line 142, in after_train
    h.after_train()
  File "/home/prj/BCNet-main/detectron2/engine/hooks.py", line 353, in after_train
    self._do_eval()
  File "/home/prj/BCNet-main/detectron2/engine/hooks.py", line 321, in _do_eval
    results = self._func()
  File "/home/prj/BCNet-main/detectron2/engine/defaults.py", line 324, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/prj/BCNet-main/detectron2/engine/defaults.py", line 484, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/prj/BCNet-main/detectron2/evaluation/evaluator.py", line 122, in inference_on_dataset
    outputs = model(inputs, idx, len(data_loader))
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 4 were given

Thank you very much for your work and admire your detailed answers in each issue，your spirit of scientific research is admirable
