### ISSUE TITLE
Dataset 'balloon_train' is not registered!

### ISSUE THREAD

**Issue by ZarrarAhmedKhan** [lkeab/BCNet#74]
Hey, I didn't get this point.
After registered the "balloon_train", why I got this error, kindly get into this. Thanks

Registering the dataset like this

>from detectron2.data.datasets import register_coco_instances

>register_coco_instances("balloon_train", {}, "json_annotation_train.json", "BCNet/datasets/balloon/train")

>register_coco_instances("balloon_val", {}, "json_annotation_val.json", "BCNet/datasets/balloon/val")

After this , when I checked its registered, 

*from detectron2.data import MetadataCatalog*

*balloon_metadata = MetadataCatalog.get("balloon_train")*

*balloon_metadata*

>Metadata(evaluator_type='coco', image_root='BCNet/datasets/balloon/train', json_file='json_annotation_train.json', name='balloon_train')

And then I got error  after running all.sh:

run on colab

*!bash all.sh*

>dataset_names: ('balloon_train',)
Traceback (most recent call last):
  File "/content/drive/MyDrive/vision/BCNet/detectron2/data/catalog.py", line 54, in get
    f = DatasetCatalog._REGISTERED[name]
KeyError: 'balloon_train'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "tools/train_net.py", line 172, in <module>
    args=(args,),
  File "/content/drive/MyDrive/vision/BCNet/detectron2/engine/launch.py", line 51, in launch
    main_func(*args)
  File "tools/train_net.py", line 154, in main
    trainer = Trainer(cfg)
  File "/content/drive/MyDrive/vision/BCNet/detectron2/engine/defaults.py", line 246, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/content/drive/MyDrive/vision/BCNet/detectron2/engine/defaults.py", line 420, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/content/drive/MyDrive/vision/BCNet/detectron2/data/build.py", line 306, in build_detection_train_loader
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/content/drive/MyDrive/vision/BCNet/detectron2/data/build.py", line 226, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/content/drive/MyDrive/vision/BCNet/detectron2/data/build.py", line 226, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/content/drive/MyDrive/vision/BCNet/detectron2/data/catalog.py", line 58, in get
    name, ", ".join(DatasetCatalog._REGISTERED.keys())
KeyError: "Dataset 'balloon_train' is not registered! Available datasets are: coco_2014_train, ....."

**Comment by lkeab** [comment]
Hi, are you following this [document](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html#register-a-coco-format-dataset) on dataset usage?

**Comment by ZarrarAhmedKhan** [comment]
Thanks for the reply.
Yes, I checked it before but there is also given " Colab tutorial ". That colab is running fine but I didn't get your repo why its not working. I have issue of "Dataset Preparation". Is there any doc for custom dataset?

**Comment by lkeab** [comment]
Hope [this](https://github.com/facebookresearch/detectron2/issues/575) can help.

**Comment by ZarrarAhmedKhan** [comment]
I done same as in the mentioned doc for the "*balloon dataset*"

*train.py*
>from detectron2.data import DatasetCatalog
name='balloon_train'
json_file='balloon/train/via_region_data.json'
image_root='/content/drive/MyDrive/vision/Detectron2/balloon/train'
DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name)) 

*Error*
>Traceback (most recent call last):
  File "train.py", line 35, in <module>
    trainer = DefaultTrainer(cfg) 
  File "/content/drive/My Drive/vision/Detectron2/BCNet/detectron2/engine/defaults.py", line 246, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/content/drive/My Drive/vision/Detectron2/BCNet/detectron2/engine/defaults.py", line 420, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/content/drive/My Drive/vision/Detectron2/BCNet/detectron2/data/build.py", line 306, in build_detection_train_loader
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/content/drive/My Drive/vision/Detectron2/BCNet/detectron2/data/build.py", line 226, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/content/drive/My Drive/vision/Detectron2/BCNet/detectron2/data/build.py", line 226, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/content/drive/My Drive/vision/Detectron2/BCNet/detectron2/data/catalog.py", line 61, in get
    return f()
  File "train.py", line 18, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/content/drive/My Drive/vision/Detectron2/BCNet/detectron2/data/datasets/coco.py", line 233, in load_coco_json
    cat_ids = sorted(coco_api.getCatIds())
  File "/usr/local/lib/python3.7/dist-packages/pycocotools/coco.py", line 168, in getCatIds
    cats = self.dataset['categories']
KeyError: 'categories'

**Comment by lkeab** [comment]
then you should print out what keys are available in 'self.dataset'
