### ISSUE TITLE
AssertionError: Checkpoint detectron2://ImageNetPretrained/MSRA/R-50.pkl not found!

### ISSUE THREAD

**Issue by leedoge** [lkeab/BCNet#77]
Hello, author. After reading your excellent works, I have successfully configured the environment, but I encountered some problems in the operation process:
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/dspldq/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/dspldq/BCNet/detectron2/engine/launch.py", line 83, in _distributed_worker
    main_func(*args)
  File "/home/dspldq/BCNet/tools/train_net.py", line 144, in main
    trainer.resume_or_load(resume=args.resume)
  File "/home/dspldq/BCNet/detectron2/engine/defaults.py", line 283, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume).get(
  File "/home/dspldq/anaconda3/envs/bcnet/lib/python3.7/site-packages/fvcore-0.1.5.post20211023-py3.7.egg/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/dspldq/anaconda3/envs/bcnet/lib/python3.7/site-packages/fvcore-0.1.5.post20211023-py3.7.egg/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint detectron2://ImageNetPretrained/MSRA/R-50.pkl not found!

I don't know where to download this pre-trained model, and where to put it, or where to modify the file path, looking forward to your reply

**Comment by lkeab** [comment]
This pkl file will be automatically downloaded running detectron2. Does your server have network connection? The issue could be related to your installation or environment setup. Please refer to https://github.com/Majiker/BalancedMetaSoftmax-InstanceSeg/issues/3
