### ISSUE TITLE
Using with latest version of Detectron2

### ISSUE THREAD

**Issue by Shadercloud** [lkeab/BCNet#81]
Is it possible to use your model with the latest version of detectron2?  I'm currently using detectron2 with good results (but not good for occluded objects). 

I'm using CUDA 11, but your repo appears to be built on an older version of detectron2 with cuda 10.

Is it possible to just merge certain files into my existing detectron2 files and then use your model configs?  (If so what files to merge?)

**Comment by lkeab** [comment]
You could download the detectron2 with support to CUDA 11, and then you could replace its mask head file with [ours](https://github.com/lkeab/BCNet/blob/main/detectron2/modeling/roi_heads/mask_head.py) and some dataset reading parts. Note that there will be some minor difference you need to adapt due to the version/api differences of detectron2.

**Comment by Shadercloud** [comment]
Using a fresh copy of Detectron2 I then added or updated the following files to resolve errors as I went along.
```
new file:   configs/Base-FCOS-test-2x.yaml
new file:   configs/Base-FCOS-test-3x.yaml
new file:   configs/Base-FCOS.yaml
new file:   configs/fcos/fcos_imprv_R_101_FPN.yaml
new file:   configs/fcos/fcos_imprv_R_50_FPN.yaml
modified:   detectron2/config/defaults.py
modified:   detectron2/layers/__init__.py
new file:   detectron2/layers/boundary.py
new file:   detectron2/layers/iou_loss.py
new file:   detectron2/layers/misc.py
new file:   detectron2/layers/scale.py
modified:   detectron2/modeling/__init__.py
modified:   detectron2/modeling/meta_arch/fcos.py
new file:   detectron2/modeling/meta_arch/fcos.py.bk
new file:   detectron2/modeling/meta_arch/inference_fcos.py
new file:   detectron2/modeling/meta_arch/loss_fcos.py
modified:   detectron2/modeling/roi_heads/__init__.py
modified:   detectron2/modeling/roi_heads/mask_head.py
```

I've got it to the point where train_net.py will run, but then it errors out during the training.  Do you have any idea how I can fix this?

```
[02/10 18:17:22 d2.engine.hooks]: Total training time: 0:00:06 (0:00:00 on hooks)
[02/10 18:17:22 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 343M
Traceback (most recent call last):
  File "train_net.py", line 162, in <module>
    launch(
  File "/home/david/code/hockey/CNN/detectron2/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/david/code/hockey/CNN/detect/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/david/code/hockey/CNN/detect/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/david/code/hockey/CNN/detect/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/david/code/hockey/CNN/detect/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/david/code/hockey/CNN/detectron2/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/home/david/code/hockey/CNN/detectron2/tools/train_net.py", line 156, in main
    return trainer.train()
  File "/home/david/code/hockey/CNN/detectron2/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/david/code/hockey/CNN/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/david/code/hockey/CNN/detectron2/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/david/code/hockey/CNN/detectron2/detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/home/david/code/hockey/CNN/detect/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/david/code/hockey/CNN/detect/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/david/code/hockey/CNN/detect/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'c_iter' and 'max_iter'
```
Here is a pastebin of the entire training command output: https://pastebin.com/70W8A6zy

Note that if I can get this working I'll create a full write up of how people can merge your code with the latest Detectron2.

**Comment by lkeab** [comment]
Thanks for the help.

**Comment by kieranatkins** [comment]
Hi,
I am trying to use @Shadercloud 's merged D2 library, and after copying the BCNet `detection_utils.py` `annotations_to_instances` method to the new library I could begin training, however after 50 iterations the `loss_cls` reaches infinity and an exception is caused. What might cause the the loss to reach infinity/0 like this?

This is being run on a custom dataset, that has been run through the preprocessing script included. Thanks.

`FloatingPointError: Loss became infinite or NaN at iteration=61!
loss_dict = {'loss_cls': inf, 'loss_reg': 0.0, 'loss_centerness': 0.0, 'loss_mask': 0.7118306756019592, 'loss_mask_bo': 0.0, 'loss_boundary_bo': 0.0, 'loss_boundary': 0.5922521352767944}`

**Comment by ttaggg** [comment]
@Shadercloud 
I think there are several modifications to the code in your repo should be done to load pretrained weights for fcos_imprv_R_101_FPN.yaml.

1. in detectron2.detectron2.modeling.backbone.fpn.LastLevelP6P7: `self.in_feature = "p5"`
2. in detectron2.detectron2.modeling.backbone.fpn.LastLevelP6P7: `self.p6 = nn.Conv2d(out_channels, out_channels, 3, 2, 1)`
3. in detectron2.detectron2.config.defaults: `_C.MODEL.ROI_MASK_HEAD.CLS_AGNOSTIC_MASK = True`

**Comment by SuperLuu7** [comment]
> 你好， 我正在尝试使用 @Shadercloud的合并D2库，并复制BCNet后 `detection_utils.py` `annotations_to_instances`我可以开始训练新库的方法，但是在 50 次迭代之后 `loss_cls`达到无穷大并引发异常。 什么可能导致损失像这样达到无穷大/0？
> 
> 这是在自定义数据集上运行的，该数据集已通过包含的预处理脚本运行。 谢谢。
> 
> `FloatingPointError: Loss became infinite or NaN at iteration=61! loss_dict = {'loss_cls': inf, 'loss_reg': 0.0, 'loss_centerness': 0.0, 'loss_mask': 0.7118306756019592, 'loss_mask_bo': 0.0, 'loss_boundary_bo': 0.0, 'loss_boundary': 0.5922521352767944}`

I ran into a similar problem. How did you solve it in the end? 
My log:
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/media/data/lilulu/BCNet-main/detectron2/engine/launch.py", line 51, in launch
    main_func(*args)
  File "tools/train_net.py", line 149, in main
    return trainer.train()
  File "/media/data/lilulu/BCNet-main/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/media/data/lilulu/BCNet-main/detectron2/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/media/data/lilulu/BCNet-main/detectron2/engine/train_loop.py", line 214, in run_step
    self._detect_anomaly(losses, loss_dict)
  File "/media/data/lilulu/BCNet-main/detectron2/engine/train_loop.py", line 237, in _detect_anomaly
    self.iter, loss_dict
FloatingPointError: Loss became infinite or NaN at iteration=4214!
loss_dict = {'loss_cls': tensor(nan, device='cuda:0', grad_fn=<DivBackward0>), 'loss_reg': tensor(nan, device='cuda:0', grad_fn=<MulBackward0>), 'loss_centerness': tensor(nan, device='cuda:0', grad_fn=<DivBackward0>), 'loss_mask': tensor(nan, device='cuda:0', grad_fn=<BinaryCrossEntropyWithLogitsBackward>), 'loss_mask_bo': tensor(nan, device='cuda:0', grad_fn=<MulBackward0>), 'loss_boundary_bo': tensor(nan, device='cuda:0', grad_fn=<MulBackward0>), 'loss_boundary': tensor(nan, device='cuda:0', grad_fn=<MulBackward0>)}
