### ISSUE TITLE
Non-existent config key: MODEL.FCOS

### ISSUE THREAD

**Issue by kieranatkins** [lkeab/BCNet#92]
Hi all,

Testing `train_net.py` using the command `python tools/train_net.py --config-file configs/fcos/fcos_imprv_R_50_FPN.yaml` returns:

`Traceback (most recent call last):
  File "/lustrehome/home/a.kia5/bcnet/detectron2/tools/train_net.py", line 156, in <module>
    launch(
  File "/home/a.kia5/.conda/envs/d2/lib/python3.9/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/lustrehome/home/a.kia5/bcnet/detectron2/tools/train_net.py", line 125, in main
    cfg = setup(args)
  File "/lustrehome/home/a.kia5/bcnet/detectron2/tools/train_net.py", line 117, in setup
    cfg.merge_from_file(args.config_file)
  File "/home/a.kia5/.conda/envs/d2/lib/python3.9/site-packages/detectron2/config/config.py", line 69, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/a.kia5/.conda/envs/d2/lib/python3.9/site-packages/fvcore/common/config.py", line 132, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/a.kia5/.conda/envs/d2/lib/python3.9/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/a.kia5/.conda/envs/d2/lib/python3.9/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/a.kia5/.conda/envs/d2/lib/python3.9/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.FCOS'
`

It seems that this error is caused by not adding custom configs, like `add_densepose_config()` for densepose, but even for the standard `train_net.py` it fails.

Any help would be appreciated.

**Comment by lkeab** [comment]
Have you followed our install instructions [here](https://github.com/lkeab/BCNet#step-by-step-installation)?

**Comment by kieranatkins** [comment]
Hi,

Yes I was an idiot here, it turns out my bash script was activating the wrong anaconda environment and was using the default detectron2 install. Apologies!
