### ISSUE TITLE
Error reporting for training own dataset

### ISSUE THREAD

**Issue by sssjing** [lkeab/BCNet#93]
hi lkeab,first of all, thank you very much for your work
我按照detectron2要求放入coco格式数据集并及新建train.py文件 注册数据集并且已经打印出图片信息
register_coco_instances("custom", {}, "datasets/coco/annotations/instances_train2017.json", "datasets/coco/train2017")
    custom_metadata = MetadataCatalog.get("custom")
    dataset_dicts = DatasetCatalog.get("custom")
    for d in random.sample(dataset_dicts, 8):
        img = cv2.imread(d["file_name"])
        #print(img)
        visualizer = Visualizer(img[:, :, ::-1], metadata=custom_metadata, scale=1)
        vis = visualizer.draw_dataset_dict(d)
        cv2.imshow('Sample',vis.get_image()[:, :, ::-1])
        cv2.waitKey(1500)
   

#train
   cfg = get_cfg()
    cfg.merge_from_file(
        "configs/fcos/fcos_imprv_R_50_FPN.yaml"
    )
    cfg.DATASETS.TRAIN = ("custom",)
    cfg.DATASETS.TEST = ()
    #cfg.DATASETS.TEST = ()
    cfg.DATALOADER.NUM_WORKERS = 4
    cfg.MODEL.WEIGHTS = 'detectron2://ImageNetPretrained/MSRA/R-50.pkl'
    cfg.SOLVER.IMS_PER_BATCH = 2
    cfg.SOLVER.BASE_LR = 0.02
    cfg.SOLVER.MAX_ITER = (
        3000
    )  
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (
        128
    ) 
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1 

    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = DefaultTrainer(cfg)
    trainer.resume_or_load(resume=False)
    trainer.train()   
训练后打印的截取的日志错误如下：
[04/04 13:47:15 d2.checkpoint.c2_model_loading]: The checkpoint state_dict contains keys that are not used by the model:
  fc1000_b
  fc1000_w
  conv1_b
[04/04 13:47:15 d2.engine.train_loop]: Starting training from iteration 0
[04/04 13:47:15 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
Traceback (most recent call last):
  File "TrainAndPredict.py", line 94, in <module>
    Train()
  File "TrainAndPredict.py", line 60, in Train
    trainer.train()    
  File "/home/miaoteng/BCNet2/BCNet/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/miaoteng/BCNet2/BCNet/detectron2/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/home/miaoteng/BCNet2/BCNet/detectron2/engine/train_loop.py", line 205, in run_step
    data = next(self._data_loader_iter)
  File "/home/miaoteng/BCNet2/BCNet/detectron2/data/common.py", line 139, in __iter__
    for d in self.dataset:
  File "/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/miaoteng/BCNet2/BCNet/detectron2/data/common.py", line 40, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/miaoteng/BCNet2/BCNet/detectron2/utils/serialize.py", line 22, in __call__
    return self._obj(*args, **kwargs)
  File "/home/miaoteng/BCNet2/BCNet/detectron2/data/dataset_mapper.py", line 76, in __call__
    image = utils.read_image(dataset_dict["file_name"], format=self.img_format)
  File "/home/miaoteng/BCNet2/BCNet/detectron2/data/detection_utils.py", line 53, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/fvcore/common/file_io.py", line 575, in open
    path, mode, buffering=buffering, **kwargs
  File "/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/fvcore/common/file_io.py", line 380, in _open
    opener=opener,
FileNotFoundError: [Errno 2] 没有那个文件或目录: '_0056.JPG'
can you help me ?

**Comment by sssjing** [comment]
I place my dataset according to datasets/coco/annotations/instances_train2017.json and datasets/coco/train2017, where _0056.JPG is placed inside train2017, is there any requirement for image naming format?

**Comment by sssjing** [comment]
ok thanks !
I have solved this problem.

**Comment by kieran0625** [comment]
Hello, may I ask if this problem is a data format naming problem? I also encountered the same problem
