### ISSUE TITLE
RuntimeError: shape '[2, 80, 68, 116]' is invalid for input of size 15776

### ISSUE THREAD

**Issue by zhangyufeng1998** [lkeab/BCNet#96]
Hello!
I register the datasets according to your method, annotate my datasets with process.sh to generate ann.json. I renamed it instances_train2017.json and put it in the directory for training, and the error log looks like this. I even changed the datasets, how to solve it ? Thank you for the advice
[04/10 16:01:20 d2.engine.train_loop]: Starting training from iteration 0
/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/fvcore/transforms/transform.py:630: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  for poly in cropped:
[04/10 16:01:22 d2.engine.hooks]: Total training time: 0:00:01 (0:00:00 on hooks)
Traceback (most recent call last):
  File "tools/train_net.py", line 217, in <module>
    args=(args,),
  File "/home/miaoteng/BCNet2/BCNet/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 204, in main
    return trainer.train()
  File "/home/miaoteng/BCNet2/BCNet/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/miaoteng/BCNet2/BCNet/detectron2/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/home/miaoteng/BCNet2/BCNet/detectron2/engine/train_loop.py", line 211, in run_step
    loss_dict = self.model(data, self.iter, self.max_iter)
  File "/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/miaoteng/BCNet2/BCNet/detectron2/modeling/meta_arch/fcos.py", line 176, in forward
    centerness, gt_instances, batched_inputs, images, c_iter, max_iter
  File "/home/miaoteng/BCNet2/BCNet/detectron2/modeling/meta_arch/fcos.py", line 193, in _forward_train
    centerness, batched_inputs, images
  File "/home/miaoteng/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/miaoteng/BCNet2/BCNet/detectron2/modeling/meta_arch/inference_fcos.py", line 146, in forward
    box_cls = [permute_to_N_HW_K(x, num_classes) for x in box_cls]
  File "/home/miaoteng/BCNet2/BCNet/detectron2/modeling/meta_arch/inference_fcos.py", line 146, in <listcomp>
    box_cls = [permute_to_N_HW_K(x, num_classes) for x in box_cls]
  File "/home/miaoteng/BCNet2/BCNet/detectron2/modeling/meta_arch/inference_fcos.py", line 17, in permute_to_N_HW_K
    tensor = tensor.view(N, K, H, W)
RuntimeError: shape '[2, 80, 68, 116]' is invalid for input of size 15776

**Comment by lkeab** [comment]
have you made the variable "num_classes" correct?

**Comment by zhangyufeng1998** [comment]
Thanks for the advice, I fixed it.
Forgive me for trying to ask a stupid question.  I also use your pre-trained model to predict through the demo, how can I see the graph of the masked predictions ? In other words, recover the occluded mask.

**Comment by lkeab** [comment]
I don't save the pretrained model for amodal prediction. But it is very easy to training one on kins or cocoa just using our code. You could refer to the discussion [here](https://github.com/lkeab/BCNet/issues/83).
